UI improvements
CovidWorld/ios pull request #21
Opened 2020-04-19 23:57 UTC by bielikb

* All VCs now use translucent navigation bar
* Choosing empty location is not valid, alert will be fired
* Privacy Policy text follows the app font
* About App text updated to the latest version
* custom buttons were converted to system buttons == consistency & native feel

2020-04-19 23:58 UTC, bielikb commented on Covid/UI/ViewController.swift
> +        navigationController?.navigationBar.isTranslucent = true
Toto moze byt kludne sucastou napr. UIAppearance, ale zatial som to tymto smerom nepushoval

2020-04-20 00:15 UTC, bielikb commented on Covid/Base.lproj/Main.storyboard
> +                                <state key="normal" title="Bola/bol som v zahraničí alebo musím zostať v karanténe">
v11 #2

2020-04-20 00:17 UTC, bielikb commented on Covid/Base.lproj/Main.storyboard
> +                                        <string key="content">Táto aplikácia bola vytvorená slovenskými odborníkmi-dobrovoľníkmi v rekordne krátkom čase, s cieľom pomôcť v boji proti šíreniu pandémie
v11 #8

2020-04-20 07:08 UTC, anonymcek requested changes

2020-04-20 07:08 UTC, anonymcek commented on Covid/UI/ViewController.swift
> +//
licka

2020-04-20 07:08 UTC, anonymcek commented on Covid/UI/ViewController.swift
> +class ViewController: UIViewController {
nejaky `TransparentNavBarViewController`, takto to nieje uplne jasne

2020-04-20 09:03 UTC, anonymcek approved these changes

2020-04-20 09:05 UTC, merged